# Generated by Django 3.0.7 on 2020-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='Holder'),
            preserve_default=False,
        ),
    ]
