# Generated by Django 3.0.7 on 2020-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
