# Generated by Django 3.0.7 on 2020-07-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_engagement_soc_1_reliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
