# Generated by Django 3.0.7 on 2020-08-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_participant_contributing'),
    ]

    operations = [
        migrations.CreateModel(
            name='error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BooleanField(blank=True, null=True)),
                ('last_name', models.BooleanField(blank=True, null=True)),
                ('SSN', models.BooleanField(blank=True, null=True)),
                ('DOB', models.BooleanField(blank=True, null=True)),
                ('DOH', models.BooleanField(blank=True, null=True)),
                ('DOT', models.BooleanField(blank=True, null=True)),
                ('DORH', models.BooleanField(blank=True, null=True)),
                ('hours_worked', models.BooleanField(blank=True, null=True)),
                ('deferral', models.BooleanField(blank=True, null=True)),
                ('catch_up', models.BooleanField(blank=True, null=True)),
                ('eligible', models.BooleanField(blank=True, null=True)),
                ('participating', models.BooleanField(blank=True, null=True)),
                ('contributing', models.BooleanField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
            ],
        ),
        migrations.CreateModel(
            name='comparison_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BooleanField(blank=True, null=True)),
                ('last_name', models.BooleanField(blank=True, null=True)),
                ('SSN', models.BooleanField(blank=True, null=True)),
                ('DOB', models.BooleanField(blank=True, null=True)),
                ('DOH', models.BooleanField(blank=True, null=True)),
                ('DOT', models.BooleanField(blank=True, null=True)),
                ('DORH', models.BooleanField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
            ],
        ),
    ]
