# Generated by Django 3.0.7 on 2020-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comparison_error_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='error',
            name='DOH',
        ),
        migrations.RemoveField(
            model_name='error',
            name='DORH',
        ),
        migrations.RemoveField(
            model_name='error',
            name='DOT',
        ),
        migrations.RemoveField(
            model_name='error',
            name='SSN',
        ),
        migrations.RemoveField(
            model_name='error',
            name='catch_up',
        ),
        migrations.RemoveField(
            model_name='error',
            name='contributing',
        ),
        migrations.RemoveField(
            model_name='error',
            name='deferral',
        ),
        migrations.RemoveField(
            model_name='error',
            name='eligible',
        ),
        migrations.RemoveField(
            model_name='error',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='error',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='error',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='error',
            name='participating',
        ),
        migrations.AddField(
            model_name='error',
            name='error_message',
            field=models.CharField(choices=[('First name data is missing', 'First name data is missing'), ('First name data does not match previous year census', 'First name data does not match previous year census'), ('Last name data is missing', 'Last name data is missing'), ('Social Security Number data is missing', 'Social Security Number data is missing'), ('DOB data is missing', 'DOB data is missing'), ('DOB data does not match previous year census', 'DOB data does not match previous year census'), ('DOH data is missing', 'DOH data is missing'), ('DOH data does not match previous year census', 'DOH data does not match previous year census'), ('DOT data is missing', 'DOT data is missing'), ('DOT data does not match previous year census', 'DOT data does not match previous year census'), ('DORH data does not match previous year census', 'DORH data does not match previous year census'), ('Hours worked data is missing', 'Hours worked data is missing'), ('Contribution amount is over IRS limit', 'Contribution amount is over IRS limit'), ('Catch-up contribution amount is over IRS limit', 'Catch-up contribution amount is over IRS limit'), ('Employee is ineligible and is participating', 'Employee is ineligible and is participating')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='comparison_error',
        ),
    ]
