# Generated by Django 3.0.7 on 2020-08-30 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200830_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='total_EE_deferral',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='total_ER_deferral',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
